### ISSUE TITLE
RUNTIME ERROR: pe: rebuilder: unable to write section raw data

### ISSUE THREAD

**Issue by FidoHUN** [es3n1n/obfuscator#10]
I've tried this tool on a small test program, and I ran into this error.

![VirtualBox_MSEdge - Win10_23_01_2024_14_38_07](https://github.com/es3n1n/obfuscator/assets/72193667/fb327508-3943-487b-8baf-c927ea30c421)

Tested on a c, and a cpp file. I got the same result.
I tried running the command in Administrator mode, but that did not solve my problem either.

**Comment by es3n1n** [comment]
Hey, can you please upload the binary you're protecting? It would also be nice if you attached the version of the compiler you've used to compile the obfuscator. Feel free to dm me in discord `@not_es3n1n`.

**Comment by es3n1n** [comment]
Should be resolved with b6457f90fa4669433e982008f0082bc26afefceb
