### ISSUE TITLE
RUNTIME ERROR: obfuscator: got 0 functions to protect

### ISSUE THREAD

**Issue by TitanCheat** [es3n1n/obfuscator#13]
13:10:14.962 | [  info  ] random: seed is 0x5904f32cf6a0ce77
13:10:14.964 | [  info  ] main: loading binary from test.exe
13:10:14.968 | [ debug  ] pe: parsed 6 sections
13:10:14.969 | [ debug  ] pe: parsed total number of 232 relocations
13:10:14.970 | [  info  ] func_parser: discovering functions: 0%
13:10:15.026 | [ debug  ] pdb: Parsed 38 types of DBI symbols
13:10:15.058 | [  info  ] func_parser: discovering functions: 25%
13:10:15.058 | [  info  ] func_parser: discovering functions: 50%
13:10:15.062 | [  info  ] func_parser: discovering functions: 75%
13:10:15.066 | [  info  ] func_parser: discovering functions: 100% took 96 ms
13:10:15.068 | [ debug  ] func_parser: discovered 3089 functions
13:10:15.069 | [  info  ] obfuscator: setting up functions: 9223372036854775808% took 13 microseconds
13:10:15.070 | [  info  ] obfuscator: got 0 function(s) to obfuscate
13:10:15.075 | [critical] RUNTIME ERROR: obfuscator: got 0 functions to protect

It gives me this error for every .exe that I try

**Comment by dumbasPL** [comment]
have you considered specifying a function to protect?
