### ISSUE TITLE
runtime error: parsed 0 functions

### ISSUE THREAD

**Issue by 0sm1les** [es3n1n/obfuscator#17]
```
PS C:\Users\user\Desktop\obfuscator> C:\Users\user\Desktop\obfuscator\build\src\Release\obfuscator.exe ..\test.exe
09:45:08.662 | [  info  ] random: seed is 0x87ee46b82834fc34
09:45:08.666 | [  info  ] main: loading binary from ..\test.exe
09:45:08.696 | [ debug  ] pe: parsed 15 sections
09:45:08.700 | [ debug  ] pe: parsed total number of 29309 relocations
09:45:08.701 | [  info  ] func_parser: discovering functions: 0%
09:45:08.702 | [  info  ] func_parser: discovering functions: 25%
09:45:08.703 | [  info  ] func_parser: discovering functions: 50%
09:45:08.705 | [  info  ] func_parser: discovering functions: 75%
09:45:08.708 | [  info  ] func_parser: discovering functions: 100% took 7 ms
09:45:08.712 | [critical] RUNTIME ERROR: parser: Parsed 0 functions in total
```
text.exe is a golang binary, I also tried a c binary and same issue. Any idea how to fix the issue?

**Comment by es3n1n** [comment]
Hello! 
Sorry for the delayed response, but are you sure your golang compiler is generating a .map or a .pdb file with functions? Having at least one of these files is required to use this obfuscator as it obtains the function list from them.

**Comment by 0sm1les** [comment]
Hi, Thank you for the response. How would I check if my binary contains a .map or .pdb section.

**Comment by es3n1n** [comment]
> Hi, Thank you for the response. How would I check if my binary contains a .map or .pdb section.

These are not sections. 
PDB - https://en.wikipedia.org/wiki/Program_database
MAP - https://stackoverflow.com/questions/755783/whats-the-use-of-map-files-the-linker-produces

Essentially, these two are just some stuff that the linker produces along with the output binary, both of these contain some info that later would be used for debugging. The obfuscator uses these files to find the instruction RVAs and link them with their names.

**Comment by 0sm1les** [comment]
That makes sense. I don't think Golang produces .PDB and .MAP when compiling so ill just have to use this with my c files. Thank you for this project btw, its very cool.
