### ISSUE TITLE
RUNTIME ERROR: pe: duplicated rva entry

### ISSUE THREAD

**Issue by LionHackerman** [es3n1n/obfuscator#19]
obf a.exe -f main
15:56:52.897 | [  info  ] random: seed is 0xf758817f291fee
15:56:52.900 | [  info  ] main: loading binary from a.exe
15:56:52.905 | [ debug  ] pe: parsed 11 sections
15:56:52.907 | [critical] RUNTIME ERROR: pe: duplicated 0x22b000 rva entry

Tried this on two .exes. Not too sure why, mabye I need to disable a compiler setting when compiling a.exe?

**Comment by es3n1n** [comment]
Hello, can you please
* Try that again but with the obfuscator compiled from `dev` branch
* If the problem remains unsolved: upload the binary you tried to obfuscate and  a pdb/map file for it
