### ISSUE TITLE
vformat error

### ISSUE THREAD

**Issue by d3x7** [es3n1n/obfuscator#20]
hi, what settings should the project be compiled with? i am compiling vs22 and i have a problem "auto std::make_format_args<std::format_context,_Ty,char*>(_Ty &,char *&)": unable to convert argument 1 from "_Ty" to "_Ty &" to MAKE_LOGGER_METHOD, not sure how to fix this?

**Comment by es3n1n** [comment]
Hello,
Can you please post the whole output of your compiler? It might be too big for a single issue reply so consider uploading it somewhere. 
Thanks

**Comment by d3x7** [comment]
Yes, sure.
Are you talking about this?

Severity	Code	Description	Project	File	Line	Suppression State	Details
Error	C2664	'auto std::make_format_args<std::format_context,_Ty,__int64,__int64>(_Ty &,__int64 &,__int64 &)': cannot convert argument 1 from '_Ty' to '_Ty &'	C:\Users\Administrator\Source\Repos\obfuscator22\out\build\x64-release\obfuscator22	C:\Users\Administrator\source\repos\obfuscator22\src\lib\util\logger.hpp	245		

Severity	Code	Description	Project	File	Line	Suppression State	Details
Error	C2672	'vformat': no matching overloaded function found	C:\Users\Administrator\Source\Repos\obfuscator22\out\build\x64-release\obfuscator22	C:\Users\Administrator\source\repos\obfuscator22\src\lib\util\logger.hpp	245

**Comment by ALittlePatate** [comment]
Hey i have the same issue, output :

`'auto std::make_format_args<std::format_context,_Ty,__int64,__int64>(_Ty &,__int64 &,__int64 &)' : cannot convert argument 1 from 1 to '_Ty' to '_Ty &'
7>obfuscator\src\lib\util\logger.hpp(246,5): error C2664:         with
7>obfuscator\src\lib\util\logger.hpp(246,5): error C2664:         [
7>obfuscator\src\lib\util\logger.hpp(246,5): error C2664:             _Ty=uint32_t
7>obfuscator\src\lib\util\logger.hpp(246,5): error C2664:         ]
7>obfuscator\src\lib\util\logger.hpp(246,5): error C2672: 'vformat' : overloaded function not found`

note: the error messages were in french, i had to translate them. maybe that's not 100% what the compiler would say

**Comment by dumbasPL** [comment]
Fixed by #21, and yes, this is a real issue on recent MSVC versions. Recently had to fix this on some of my projects as well

**Comment by es3n1n** [comment]
Fixed in cc8f4bdda863c60e00ba6b5616ec21ab3c18bb44

**Comment by d3x7** [comment]
thx
