### ISSUE TITLE
Waiting for improvements

### ISSUE THREAD

**Issue by LenaTDDS** [es3n1n/obfuscator#24]
You said in your telegram channel:

> we type five thousand vomits on this message and I finish it

![image](https://github.com/user-attachments/assets/3488be5d-fe68-486e-81ca-837a84493abb)

But there have been no commits since then about the improvement. Should we wait?

**Comment by es3n1n** [comment]
> But there have been no commits since then about the improvement. Should we wait?

Yes, you should
