### ISSUE TITLE
Error during building with cmake

### ISSUE THREAD

**Issue by FidoHUN** [es3n1n/obfuscator#9]
![image](https://github.com/es3n1n/obfuscator/assets/72193667/7875e613-2783-43bc-a168-e3b4a9da5fb4)

I get this error during cmake building. Any idea how to solve this? Thanks!

**Comment by mariuszste** [comment]
You're missing git submodules, git cline recursively `git clone --recursive https://github.com/es3n1n/obfuscator.git` instead of downloading the zip or download all the dependencies manually

git submodule docs: https://git-scm.com/book/en/v2/Git-Tools-Submodules

**Comment by FidoHUN** [comment]
Yeah, I did not use --recursive while cloning. Thanks!
